# Generated by Django 4.0.4 on 2022-06-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apuntar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('curso', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=100)),
            ],
        ),
    ]
